version: 2

builds:
  - binary: ddcli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/ethanrcohen/ddcli/cmd.buildVersion={{.Version}}
      - -X github.com/ethanrcohen/ddcli/cmd.commit={{.Commit}}
      - -X github.com/ethanrcohen/ddcli/cmd.date={{.Date}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
